### ISSUE TITLE
Requiring camelCase instead of camelcase

### ISSUE THREAD

**Issue by mspae** [keokilee/react-electron-webview#1]
I get an error for the require statement for `camelCase`, I think it should be `camelcase` (unless I'm missing something. I'm currently fixing this by adding this postinstall property to my scripts object in package.json:

``` javascript
"postinstall": "sed -i 's/camelCase/camelcase/g' ./node_modules/react-electron-webview/index.js"
```

Thanks for this great project & keep up the good work! :+1:

**Comment by keokilee** [comment]
Finally got around to fixing this in 1.0.5. Thinking about setting up a test suite so this doesn't happen again. Thanks for filing the issue!
